otitle: Personal Blog
markdown: kramdown
url: ""
baseurl: "/geekyll-starter-blog"

# for atom feed
author:
  name: Aaron Reyes
  email: 2001reyesaaron@gmail.com
  image: "https://avatars0.githubusercontent.com/u/69468826?s=60&v=4"
  bio: Developed by <b>Sharad Raj</b> who lives in India building useful things for the world.
  github: "sharadcodes"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
